COLOUR_PRIMARY = "#1C1B2D"
COLOUR_SECONDARY = "#1C1B2D"
COLOUR_LIGHT_BACKGROUND = "#fff"
COLOUR_LIGHT_TEXT = "#eee"
COLOUR_DARK_TEXT = "#8095a8"

COLOUR_DOWNLOAD_DATA = "#47bef5"
COLOUR_UPLOAD_DATA = "#6330c9"
